# Generated by Django 5.2.5 on 2026-09-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profiles', '0003_seed_default_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteacherinstrument',
            name='skill_ceiling',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Highest student level the teacher takes on this instrument; empty = not set', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinstrument',
            name='skill_ceiling',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Highest student level the teacher takes on this instrument; empty = not set', max_length=20, null=True),
        ),
    ]
