# Generated by Django 5.2.5 on 2025-09-06 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
