# Generated by Django 5.2.5 on 2025-09-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6),
        ),
    ]
