# Generated by Django 5.2.5 on 2025-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_delete_student_alter_lesson_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
