# Generated by Django 5.2.5 on 2025-09-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_delete_student_alter_lesson_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=6),
        ),
    ]
