# Generated by Django 5.2.5 on 2025-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_make_scheduled_date_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
