# Generated by Django 5.2.5 on 2025-10-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_add_invoice_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[("online", "Online"), ("in_person", "In_person")],
                default="in_person",
                help_text="Type of lesson: online or in-person",
                max_length=20,
            ),
        ),
    ]
