# Generated by Django 5.2.5 on 2025-11-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_last_edited_at_invoice_last_edited_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user_type', models.CharField(choices=[('management', 'Management'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('approved_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to='billing.approvedemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
