# Generated by Django 5.2.5 on 2025-11-10 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_invoice_number_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'management'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible to teacher)'),
        ),
        # Note: lesson_type already exists in database, skipping
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='draft', max_length=20),
        ),
    ]
