# Generated by Django 5.2.5 on 2025-11-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_lesson_lesson_type'),
        ('billing', '0011_invoice_rejected_at_invoice_rejected_by_and_more'),
    ]

    operations = [
    ]
