# Generated by Django 5.2.5 on 2025-11-13 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_lesson_lesson_type_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRecipientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Recipient email address for invoice PDFs', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipient_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Recipient Email',
                'verbose_name_plural': 'Invoice Recipient Emails',
                'ordering': ['created_at'],
            },
        ),
    ]
