# Generated by Django 5.2.5 on 2025-11-13 13:41

from django.db import migrations


def migrate_existing_email(apps, schema_editor):
    """Migrate existing email from SystemSettings to InvoiceRecipientEmail"""
    SystemSettings = apps.get_model('billing', 'SystemSettings')
    InvoiceRecipientEmail = apps.get_model('billing', 'InvoiceRecipientEmail')

    try:
        # Get the singleton SystemSettings instance
        settings = SystemSettings.objects.get(pk=1)

        # Only migrate if email exists and is not empty
        if settings.invoice_recipient_email:
            # Create InvoiceRecipientEmail record if it doesn't exist
            InvoiceRecipientEmail.objects.get_or_create(
                email=settings.invoice_recipient_email,
                defaults={'created_by': settings.updated_by}
            )
            print(f"Migrated email: {settings.invoice_recipient_email}")
    except SystemSettings.DoesNotExist:
        print("No SystemSettings found, skipping migration")


def reverse_migration(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_invoicerecipientemail'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_email, reverse_migration),
    ]
