# Generated by Django 5.2.5 on 2025-12-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_migrate_existing_email_to_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='invoice_recipient_email',
            field=models.EmailField(help_text='Email address where invoice PDFs are sent', max_length=254),
        ),
    ]
