# Generated by Django 5.2.5 on 2025-12-17 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_systemsettings_invoice_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Rate billed to student for this lesson', max_digits=6),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Rate paid to teacher for this lesson', max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='GlobalRateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_teacher_rate', models.DecimalField(decimal_places=2, default=45.0, help_text='Rate paid to teachers for online lessons ($/hour)', max_digits=6)),
                ('online_student_rate', models.DecimalField(decimal_places=2, default=60.0, help_text='Rate billed to students for online lessons ($/hour)', max_digits=6)),
                ('inperson_student_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Rate billed to students for in-person lessons ($/hour). Teachers paid their hourly_rate.', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Rate Settings',
                'verbose_name_plural': 'Global Rate Settings',
            },
        ),
    ]
