# Generated by Django 5.2.5 on 2025-12-17 11:50

from decimal import Decimal
from django.db import migrations


def backfill_lesson_rates(apps, schema_editor):
    """
    Backfill teacher_rate and student_rate for existing lessons.

    Logic:
    - Online lessons: teacher_rate = $45, student_rate = $60
    - In-person lessons: teacher_rate = current 'rate' field, student_rate = $100
    """
    Lesson = apps.get_model('billing', 'Lesson')

    # Update online lessons
    online_lessons = Lesson.objects.filter(lesson_type='online')
    for lesson in online_lessons:
        lesson.teacher_rate = Decimal('45.00')
        lesson.student_rate = Decimal('60.00')
        lesson.save()

    # Update in-person lessons
    inperson_lessons = Lesson.objects.filter(lesson_type='in_person')
    for lesson in inperson_lessons:
        # Keep existing rate as teacher_rate (locked at lesson creation)
        lesson.teacher_rate = lesson.rate
        lesson.student_rate = Decimal('100.00')
        lesson.save()


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - reset to default values
    """
    Lesson = apps.get_model('billing', 'Lesson')

    # Reset all lessons to defaults
    Lesson.objects.all().update(
        teacher_rate=Decimal('50.00'),
        student_rate=Decimal('100.00')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_add_dual_rate_system'),
    ]

    operations = [
        migrations.RunPython(backfill_lesson_rates, reverse_backfill),
    ]
