# Generated by Django 5.2.5 on 2026-01-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_backfill_lesson_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Trial lesson - student not charged, teacher still paid'),
        ),
    ]
