# Generated by Django 5.2.5 on 2026-01-26 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_add_trial_lesson_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag - False means user is deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='DEPRECATED: Use BillableContact instead', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use BillableContact instead', max_length=15),
        ),
        migrations.CreateModel(
            name='BillableContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('self', 'Self'), ('other', 'Other')], default='parent', max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='Province/State code', max_length=2)),
                ('postal_code', models.CharField(help_text='Postal code (e.g., A1A 1A1) or ZIP code', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact receives invoices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='billable_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billable Contact',
                'verbose_name_plural': 'Billable Contacts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
