# Generated by Django 5.2.5 on 2026-01-26 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_migrate_student_data'),
    ]

    operations = [
        # Note: assigned_teacher field never existed in production User model
        # (it was only in the old Student model which was separate)
        # Skip RemoveField operation
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag - False means user is deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='DEPRECATED: Use BillableContact instead', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use BillableContact instead', max_length=15),
        ),
        # Register BillableContact with Django's state (table already exists from 0020)
        # Use state_operations only - no database operations since table was created in 0020
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BillableContact',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('contact_type', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('self', 'Self'), ('other', 'Other')], default='parent', max_length=20)),
                        ('first_name', models.CharField(max_length=150)),
                        ('last_name', models.CharField(max_length=150)),
                        ('email', models.EmailField(max_length=254)),
                        ('phone', models.CharField(max_length=15)),
                        ('street_address', models.CharField(max_length=255)),
                        ('city', models.CharField(max_length=100)),
                        ('state', models.CharField(help_text='Province/State code', max_length=2)),
                        ('postal_code', models.CharField(help_text='Postal code (e.g., A1A 1A1) or ZIP code', max_length=10)),
                        ('is_primary', models.BooleanField(default=False, help_text='Primary contact receives invoices')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='billable_contacts', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Billable Contact',
                        'verbose_name_plural': 'Billable Contacts',
                        'ordering': ['-is_primary', '-created_at'],
                    },
                ),
            ],
            database_operations=[],  # No database operations - table already exists
        ),
        # Register User.assigned_teachers many-to-many field with Django's state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='assigned_teachers',
                    field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],  # No database operations - table already created in 0020
        ),
    ]
