# Generated by Django 5.2.5 on 2026-02-11 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_remove_obsolete_user_address_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subdomain', models.SlugField(help_text='Used for the URL', max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('hst_rate', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('pst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('billing_cycle_day', models.PositiveIntegerField(help_text='Day of the month (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('payment_terms_days', models.PositiveIntegerField(default=7)),
                ('cancellation_notice_hours', models.PositiveIntegerField(default=24)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(default='ON', max_length=2)),
                ('postal_code', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='billing.school'),
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_teacher_rate', models.DecimalField(decimal_places=2, default=45.0, max_digits=6)),
                ('online_student_rate', models.DecimalField(decimal_places=2, default=60.0, max_digits=6)),
                ('inperson_student_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('invoice_recipient_email', models.EmailField(blank=True, help_text='DEPRECATED', max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='billing.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
