# Generated by Django 5.2.5 on 2026-02-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_remove_billablecontact_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='School this invoice belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school'),
        ),
        migrations.AddField(
            model_name='historicalinvoicerecipientemail',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='School this invoice recipient belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this invoice belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.school'),
        ),
        migrations.AddField(
            model_name='invoicerecipientemail',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this invoice recipient belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_recipient_emails', to='billing.school'),
        ),
    ]
