# Generated by Django 5.2.5 on 2026-02-18 16:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_make_school_fks_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecurringLessonsSchedule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Lesson start time (eg. 15:00)')),
                ('duration', models.DecimalField(decimal_places=2, default=1.0, help_text='Duration in hours', max_digits=4)),
                ('lesson_type', models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], default='in_person', max_length=20)),
                ('teacher_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to pause/end this recurring schedule')),
                ('start_date', models.DateField(help_text='When this recurring schedule begins')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date to track', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Recurring Lesson Schedule',
                'verbose_name_plural': 'historical Recurring Lesson Schedules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RecurringLessonsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Lesson start time (eg. 15:00)')),
                ('duration', models.DecimalField(decimal_places=2, default=1.0, help_text='Duration in hours', max_digits=4)),
                ('lesson_type', models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], default='in_person', max_length=20)),
                ('teacher_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to pause/end this recurring schedule')),
                ('start_date', models.DateField(help_text='When this recurring schedule begins')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date to track', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_lesson_schedules', to='billing.school')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_schedules', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Lesson Schedule',
                'verbose_name_plural': 'Recurring Lesson Schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('teacher', 'student', 'day_of_week', 'start_time')},
            },
        ),
    ]
