# Generated by Django 5.2.5 on 2026-02-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_historicalrecurringlessonsschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallesson',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Optional reason for cancellation'),
        ),
        migrations.AddField(
            model_name='historicallesson',
            name='cancelled_by_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher Cancelled'), ('student', 'Student Cancelled')], help_text='Who cancelled the lesson (affects billing)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicallesson',
            name='recurring_schedule',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The recurring schedule that generated this lesson', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.recurringlessonsschedule'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Optional reason for cancellation'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancelled_by_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher Cancelled'), ('student', 'Student Cancelled')], help_text='Who cancelled the lesson (affects billing)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recurring_schedule',
            field=models.ForeignKey(blank=True, help_text='The recurring schedule that generated this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lessons', to='billing.recurringlessonsschedule'),
        ),
    ]
