# Generated by Django 5.2.5 on 2026-02-18 20:07

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_historicallesson_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMonthlyInvoiceBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, help_text='The teacher payment invoice created from this batch', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'management'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Monthly Invoice Batch',
                'verbose_name_plural': 'historical Monthly Invoice Batches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MonthlyInvoiceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, help_text='The teacher payment invoice created from this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_batch', to='billing.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'management'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_batches', to='billing.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Invoice Batch',
                'verbose_name_plural': 'Monthly Invoice Batches',
                'ordering': ['-year', 'month', 'created_at'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BatchLessonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('lesson_type', models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], max_length=20)),
                ('teacher_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('cancelled_by_type', models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=20, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('is_one_off', models.BooleanField(default=False, help_text='True if teacher added this manually (not from recurring schedule)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_lesson', models.ForeignKey(blank=True, help_text='Actual Lesson record created when batch was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.lesson')),
                ('recurring_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.recurringlessonsschedule')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_items', to='billing.monthlyinvoicebatch')),
            ],
            options={
                'verbose_name': 'Batch Lesson Item',
                'verbose_name_plural': 'Batch Lesson Items',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
    ]
