# Generated by Django 5.2.5 on 2026-03-02 20:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_historicalmonthlyinvoicebatch_monthlyinvoicebatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='management_notification_email',
            field=models.EmailField(blank=True, help_text='Email for management notifications (future use)', max_length=254),
        ),
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='payment_terms',
            field=models.CharField(default='Due in 15 days', help_text='Default payment terms for student invoices', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='management_notification_email',
            field=models.EmailField(blank=True, help_text='Email for management notifications (future use)', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='payment_terms',
            field=models.CharField(default='Due in 15 days', help_text='Default payment terms for student invoices', max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricalStudentInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_contact_name', models.CharField(max_length=200)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_phone', models.CharField(max_length=20)),
                ('billing_street_address', models.CharField(max_length=200)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_province', models.CharField(max_length=2)),
                ('billing_postal_code', models.CharField(max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, help_text='The batch this invoice was generated from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.monthlyinvoicebatch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, help_text='Student this invoice is for', limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Student Invoice',
                'verbose_name_plural': 'historical Student Invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_contact_name', models.CharField(max_length=200)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_phone', models.CharField(max_length=20)),
                ('billing_street_address', models.CharField(max_length=200)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_province', models.CharField(max_length=2)),
                ('billing_postal_code', models.CharField(max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='The batch this invoice was generated from', on_delete=django.db.models.deletion.CASCADE, related_name='student_invoices', to='billing.monthlyinvoicebatch')),
                ('lesson_items', models.ManyToManyField(help_text='Completed lessons included in this invoice', related_name='student_invoice', to='billing.batchlessonitem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_invoices', to='billing.school')),
                ('student', models.ForeignKey(help_text='Student this invoice is for', limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='helcim_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Invoice',
                'verbose_name_plural': 'Student Invoices',
                'ordering': ['-generated_at'],
                'unique_together': {('batch', 'student')},
            },
        ),
    ]
