# Generated by Django 5.2.5 on 2026-03-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_phase7_management_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmonthlyinvoicebatch',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was processed', null=True),
        ),
        migrations.AddField(
            model_name='historicalmonthlyinvoicebatch',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('e-transfer', 'E-Transfer'), ('cheque', 'Cheque'), ('direct_deposit', 'Direct Deposit')], help_text='Payment method used for this batch', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoicebatch',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was processed', null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoicebatch',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('e-transfer', 'E-Transfer'), ('cheque', 'Cheque'), ('direct_deposit', 'Direct Deposit')], help_text='Payment method used for this batch', max_length=20, null=True),
        ),
    ]
