# Generated by Django 5.2.5 on 2026-05-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_historicalmonthlyinvoicebatch_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlessonitem',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
