# Generated by Django 5.2.5 on 2026-05-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_batchlessonitem_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlessonitem',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallesson',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='requested', max_length=20),
        ),
    ]
