# Generated by Django 5.2.5 on 2026-05-07 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0044_remove_user_parent_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallesson",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="parent_email",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="parent_phone",
        ),
    ]
