# Generated by Django 5.2.5 on 2026-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0046_userregistrationrequest_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchlessonitem",
            name="admin_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
