# Generated by Django 5.2.5 on 2026-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0046_userregistrationrequest_school"),
    ]

    operations = [
        # SeparateDatabaseAndState: ORM state uses AddField (so Django tracks the field),
        # but the DB operation uses IF NOT EXISTS — safe whether or not the column
        # already exists (production had it from main's 0040 migration).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="batchlessonitem",
                    name="admin_notes",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE billing_batchlessonitem ADD COLUMN IF NOT EXISTS admin_notes TEXT NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE billing_batchlessonitem DROP COLUMN IF EXISTS admin_notes;",
                ),
            ],
        ),
    ]
