# Generated by Django 5.2.5 on 2026-06-02 00:23

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_batchlessonitem_admin_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchlessonitem',
            name='cancelled_by_type',
        ),
        migrations.RemoveField(
            model_name='historicallesson',
            name='cancelled_by_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cancelled_by_type',
        ),
        migrations.AlterField(
            model_name='batchlessonitem',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('forfeited', 'Forfeited'), ('waived', 'Waived')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallesson',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('forfeited', 'Forfeited'), ('waived', 'Waived')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('forfeited', 'Forfeited'), ('waived', 'Waived')], default='requested', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalStudentCreditAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current credit balance in dollars. Always >= 0 (DB enforced).', max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, help_text='School this credit account belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Student Credit Account',
                'verbose_name_plural': 'historical Student Credit Accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StudentCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current credit balance in dollars. Always >= 0 (DB enforced).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(help_text='School this credit account belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='student_credit_accounts', to='billing.school')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Credit Account',
                'verbose_name_plural': 'Student Credit Accounts',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCreditTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('pre_billing_payment', 'Pre-Billing Payment'), ('forfeited', 'Forfeited'), ('waived_rollover', 'Waived Rollover')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Direction determined by type field.', max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, help_text='Denormalized for school-isolation queries — do not remove', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.studentcreditaccount')),
            ],
            options={
                'verbose_name': 'historical Credit Transaction',
                'verbose_name_plural': 'historical Credit Transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pre_billing_payment', 'Pre-Billing Payment'), ('forfeited', 'Forfeited'), ('waived_rollover', 'Waived Rollover')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Direction determined by type field.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(help_text='Denormalized for school-isolation queries — do not remove', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='billing.school')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.studentcreditaccount')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentcreditaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='credit_account_balance_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcreditaccount',
            unique_together={('student', 'school')},
        ),
    ]
