# Generated by Django 5.2.5 on 2026-06-02 15:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0048_phase17_terminology_credit_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credittransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Always positive. Direction determined by type field.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcredittransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Always positive. Direction determined by type field.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="credittransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="credit_transaction_amount_positive",
            ),
        ),
    ]
