# Generated by Django 5.2.5 on 2026-06-02 19:25

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_credit_transaction_amount_positive'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelcimWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helcim_transaction_id', models.CharField(help_text='Idempotency key — unique per Helcim transaction. Duplicate POSTs are no-ops.', max_length=100, unique=True)),
                ('raw_payload', models.JSONField(help_text='Full webhook body stored for debugging and audit. PCI-safe: Helcim sends only id/type, no card data.')),
                ('invoice_id', models.CharField(blank=True, help_text='invoiceNumber from secondary GET call in Plan 03. Blank until secondary GET completes.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment amount. Always use Decimal(str(value)) when converting from Helcim JSON.', max_digits=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, help_text='Set by Phase 20 credit reconciliation. Null until invoice resolved.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='helcim_webhook_events', to='billing.school')),
            ],
            options={
                'verbose_name': 'Helcim Webhook Event',
                'verbose_name_plural': 'Helcim Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHelcimWebhookEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('helcim_transaction_id', models.CharField(db_index=True, help_text='Idempotency key — unique per Helcim transaction. Duplicate POSTs are no-ops.', max_length=100)),
                ('raw_payload', models.JSONField(help_text='Full webhook body stored for debugging and audit. PCI-safe: Helcim sends only id/type, no card data.')),
                ('invoice_id', models.CharField(blank=True, help_text='invoiceNumber from secondary GET call in Plan 03. Blank until secondary GET completes.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment amount. Always use Decimal(str(value)) when converting from Helcim JSON.', max_digits=10)),
                ('received_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, help_text='Set by Phase 20 credit reconciliation. Null until invoice resolved.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
            ],
            options={
                'verbose_name': 'historical Helcim Webhook Event',
                'verbose_name_plural': 'historical Helcim Webhook Events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
