# Generated by Django 5.2.5 on 2026-06-03 14:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0050_helcim_webhook_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='billablecontact',
            name='helcim_customer_id',
            field=models.CharField(blank=True, help_text='Helcim customer ID — set on first invoice send, never changed. PCI-safe: no card data.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbillablecontact',
            name='helcim_customer_id',
            field=models.CharField(blank=True, help_text='Helcim customer ID — set on first invoice send, never changed. PCI-safe: no card data.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalPreBillingInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('adjusted', 'Adjusted'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount locked at draft generation. Floor at 0 enforced in view layer (D-05).', max_digits=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('helcim_invoice_id', models.CharField(blank=True, help_text='Helcim invoice ID — populated after send (BILL-07). PCI-safe: no card data.', max_length=100)),
                ('payment_token', models.CharField(blank=True, help_text='Raw Helcim hosted-payment token (not the full URL). URL built as: https://{HELCIM_SUBDOMAIN}.myhelcim.com/order/?token={payment_token}', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pre-Billing Invoice',
                'verbose_name_plural': 'historical Pre-Billing Invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PreBillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('adjusted', 'Adjusted'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount locked at draft generation. Floor at 0 enforced in view layer (D-05).', max_digits=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('helcim_invoice_id', models.CharField(blank=True, help_text='Helcim invoice ID — populated after send (BILL-07). PCI-safe: no card data.', max_length=100)),
                ('payment_token', models.CharField(blank=True, help_text='Raw Helcim hosted-payment token (not the full URL). URL built as: https://{HELCIM_SUBDOMAIN}.myhelcim.com/order/?token={payment_token}', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessons', models.ManyToManyField(blank=True, related_name='pre_billing_invoices', to='billing.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_billing_invoices', to='billing.school')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='pre_billing_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-Billing Invoice',
                'verbose_name_plural': 'Pre-Billing Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
