# Generated by Django 5.2.5 on 2026-06-04 16:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0051_pre_billing_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentinvoice',
            name='amount_after_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually charged to student = PreBillingInvoice.amount for this period. Falls back to StudentInvoice.amount if no PreBillingInvoice exists.', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalstudentinvoice',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rollover credit applied to reduce this invoice. StudentInvoice.amount (gross) minus PreBillingInvoice.amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='amount_after_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually charged to student = PreBillingInvoice.amount for this period. Falls back to StudentInvoice.amount if no PreBillingInvoice exists.', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rollover credit applied to reduce this invoice. StudentInvoice.amount (gross) minus PreBillingInvoice.amount.', max_digits=10),
        ),
    ]
