# Generated by Django 5.2.5 on 2026-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0055_school_expense_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prebillinginvoice',
            constraint=models.UniqueConstraint(fields=('student', 'school', 'period_start'), name='unique_prebilling_per_student_period'),
        ),
    ]
