# Generated by Django 5.2.5 on 2026-06-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0056_prebillinginvoice_unique_prebilling_per_student_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalschoolmonthlyexpenses',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical school monthly expenses', 'verbose_name_plural': 'historical school monthly expensess'},
        ),
    ]
