# Generated by Django 5.2.5 on 2026-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0057_alter_historicalschoolmonthlyexpenses_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecurringlessonsschedule',
            name='pause_end',
            field=models.DateField(blank=True, help_text='End of planned leave window (inclusive). Null means pause extends indefinitely from pause_start.', null=True),
        ),
        migrations.AddField(
            model_name='historicalrecurringlessonsschedule',
            name='pause_start',
            field=models.DateField(blank=True, help_text='Start of planned leave window (inclusive). Set alongside pause_end for a bounded pause, or alone for an open-ended pause.', null=True),
        ),
        migrations.AddField(
            model_name='recurringlessonsschedule',
            name='pause_end',
            field=models.DateField(blank=True, help_text='End of planned leave window (inclusive). Null means pause extends indefinitely from pause_start.', null=True),
        ),
        migrations.AddField(
            model_name='recurringlessonsschedule',
            name='pause_start',
            field=models.DateField(blank=True, help_text='Start of planned leave window (inclusive). Set alongside pause_end for a bounded pause, or alone for an open-ended pause.', null=True),
        ),
    ]
