# Generated by Django 5.2.5 on 2026-07-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_recurringschedule_pause_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRejectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('total_teacher_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_snapshots', to='billing.monthlyinvoicebatch')),
                ('rejected_by', models.ForeignKey(limit_choices_to={'user_type': 'management'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.school')),
            ],
            options={
                'ordering': ['-rejected_at'],
            },
        ),
    ]
