# Generated by Django 5.2.5 on 2026-07-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0059_batchrejectionsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='waive_limit',
            field=models.PositiveIntegerField(default=3, help_text='Waived cancellations allowed per period'),
        ),
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='waive_limit_enabled',
            field=models.BooleanField(default=False, help_text='Enforce the waived-cancellation limit'),
        ),
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='waive_period_end',
            field=models.DateField(blank=True, help_text='Fixed period end (fixed type)', null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='waive_period_months',
            field=models.PositiveIntegerField(default=4, help_text='Rolling window length in months (rolling type)'),
        ),
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='waive_period_recurring',
            field=models.BooleanField(default=True, help_text='Fixed period repeats every year (month/day match)'),
        ),
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='waive_period_start',
            field=models.DateField(blank=True, help_text='Fixed period start (fixed type)', null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='waive_period_type',
            field=models.CharField(choices=[('rolling', 'Rolling window (last N months)'), ('fixed', 'Fixed dates')], default='rolling', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='waive_limit',
            field=models.PositiveIntegerField(default=3, help_text='Waived cancellations allowed per period'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='waive_limit_enabled',
            field=models.BooleanField(default=False, help_text='Enforce the waived-cancellation limit'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='waive_period_end',
            field=models.DateField(blank=True, help_text='Fixed period end (fixed type)', null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='waive_period_months',
            field=models.PositiveIntegerField(default=4, help_text='Rolling window length in months (rolling type)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='waive_period_recurring',
            field=models.BooleanField(default=True, help_text='Fixed period repeats every year (month/day match)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='waive_period_start',
            field=models.DateField(blank=True, help_text='Fixed period start (fixed type)', null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='waive_period_type',
            field=models.CharField(choices=[('rolling', 'Rolling window (last N months)'), ('fixed', 'Fixed dates')], default='rolling', max_length=10),
        ),
    ]
