# Generated by Django 5.2.5 on 2026-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0060_historicalschoolsettings_waive_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='helcim_invoice_number',
            field=models.CharField(blank=True, help_text='Helcim invoiceNumber (e.g. INV1791) from create_invoice response. Payment/webhook responses reference invoiceNumber, not invoiceId — this is the field webhook reconciliation matches on.', max_length=100),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='helcim_invoice_number',
            field=models.CharField(blank=True, help_text='Helcim invoiceNumber (e.g. INV1791) from create_invoice response. Payment/webhook responses reference invoiceNumber, not invoiceId — this is the field webhook reconciliation matches on.', max_length=100),
        ),
    ]
