# Generated by Django 5.2.5 on 2026-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0061_historicalprebillinginvoice_helcim_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmonthlyinvoicebatch',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this batch was archived off the Payroll lists. Null = active.', null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoicebatch',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this batch was archived off the Payroll lists. Null = active.', null=True),
        ),
    ]
