# Generated by Django 5.2.5 on 2026-08-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_historicalmonthlyinvoicebatch_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helcimwebhookevent',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last processing error detail, for admin review.'),
        ),
        migrations.AddField(
            model_name='helcimwebhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When credit reconciliation last completed (any terminal outcome).', null=True),
        ),
        migrations.AddField(
            model_name='helcimwebhookevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('credited_partial', 'Credited (partial)'), ('not_approved', 'Not approved'), ('non_purchase', 'Non-purchase'), ('no_invoice', 'No matching invoice'), ('no_account', 'No credit account'), ('enrichment_failed', 'Enrichment failed')], default='pending', help_text='Outcome of credit reconciliation. Retryable states are re-attempted on webhook retry or via retry_webhook_events.', max_length=30),
        ),
        migrations.AddField(
            model_name='helcimwebhookevent',
            name='transaction_status',
            field=models.CharField(blank=True, help_text='Helcim transaction status (e.g. APPROVED, DECLINED).', max_length=30),
        ),
        migrations.AddField(
            model_name='helcimwebhookevent',
            name='transaction_type',
            field=models.CharField(blank=True, help_text='Helcim transaction type (e.g. purchase, refund, reverse).', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalhelcimwebhookevent',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last processing error detail, for admin review.'),
        ),
        migrations.AddField(
            model_name='historicalhelcimwebhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When credit reconciliation last completed (any terminal outcome).', null=True),
        ),
        migrations.AddField(
            model_name='historicalhelcimwebhookevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('credited_partial', 'Credited (partial)'), ('not_approved', 'Not approved'), ('non_purchase', 'Non-purchase'), ('no_invoice', 'No matching invoice'), ('no_account', 'No credit account'), ('enrichment_failed', 'Enrichment failed')], default='pending', help_text='Outcome of credit reconciliation. Retryable states are re-attempted on webhook retry or via retry_webhook_events.', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalhelcimwebhookevent',
            name='transaction_status',
            field=models.CharField(blank=True, help_text='Helcim transaction status (e.g. APPROVED, DECLINED).', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalhelcimwebhookevent',
            name='transaction_type',
            field=models.CharField(blank=True, help_text='Helcim transaction type (e.g. purchase, refund, reverse).', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='email_error',
            field=models.TextField(blank=True, help_text='Last email delivery error. Cleared on successful send/resend.'),
        ),
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='True once the payment-request email was delivered to Resend without error.'),
        ),
        migrations.AddField(
            model_name='historicalschool',
            name='helcim_api_token',
            field=models.CharField(blank=True, help_text='Helcim API token for this school. Blank = use HELCIM_API_TOKEN env setting.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalschool',
            name='helcim_subdomain',
            field=models.CharField(blank=True, help_text='Helcim account subdomain for hosted payment URLs. Blank = use HELCIM_SUBDOMAIN env setting.', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalschool',
            name='helcim_terminal_id',
            field=models.CharField(blank=True, help_text='Helcim terminal ID. Blank = use HELCIM_TERMINAL_ID env setting.', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalschool',
            name='helcim_webhook_secret',
            field=models.CharField(blank=True, help_text='Base64 webhook verifier token. Blank = use HELCIM_WEBHOOK_SECRET env setting.', max_length=255),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='email_error',
            field=models.TextField(blank=True, help_text='Last email delivery error. Cleared on successful send/resend.'),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='True once the payment-request email was delivered to Resend without error.'),
        ),
        migrations.AddField(
            model_name='school',
            name='helcim_api_token',
            field=models.CharField(blank=True, help_text='Helcim API token for this school. Blank = use HELCIM_API_TOKEN env setting.', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='helcim_subdomain',
            field=models.CharField(blank=True, help_text='Helcim account subdomain for hosted payment URLs. Blank = use HELCIM_SUBDOMAIN env setting.', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='helcim_terminal_id',
            field=models.CharField(blank=True, help_text='Helcim terminal ID. Blank = use HELCIM_TERMINAL_ID env setting.', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='helcim_webhook_secret',
            field=models.CharField(blank=True, help_text='Base64 webhook verifier token. Blank = use HELCIM_WEBHOOK_SECRET env setting.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalinvoicerecipientemail',
            name='email',
            field=models.EmailField(help_text='Recipient email address for invoice PDFs', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalprebillinginvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('adjusted', 'Adjusted'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicerecipientemail',
            name='email',
            field=models.EmailField(help_text='Recipient email address for invoice PDFs', max_length=254),
        ),
        migrations.AlterField(
            model_name='prebillinginvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('adjusted', 'Adjusted'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoicerecipientemail',
            unique_together={('school', 'email')},
        ),
    ]
