# Generated by Django 5.2.5 on 2026-08-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0064_backfill_webhook_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalSystemSettings',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
