# Generated by Django 5.2.5 on 2026-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0065_remove_systemsettings_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, help_text="ISO dates management skipped on this bill-ahead draft (e.g. a family's known absence). Applies only to schedule-projected invoices; skipped dates drop out of the projection, amount, line items, and email. One-off — does not touch the schedule."),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, help_text="ISO dates management skipped on this bill-ahead draft (e.g. a family's known absence). Applies only to schedule-projected invoices; skipped dates drop out of the projection, amount, line items, and email. One-off — does not touch the schedule."),
        ),
    ]
