# Generated by Django 5.2.5 on 2026-09-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0068_historicalinvoicesendrun_invoicesendrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesenditem',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
