# Generated by Django 5.2.5 on 2026-09-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0070_demote_non_platform_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='source_event',
            field=models.ForeignKey(blank=True, help_text='Webhook event that posted this credit; at most one credit per event.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='billing.helcimwebhookevent'),
        ),
        migrations.AddField(
            model_name='historicalcredittransaction',
            name='source_event',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Webhook event that posted this credit; at most one credit per event.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.helcimwebhookevent'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event__isnull', False)), fields=('source_event',), name='one_credit_per_webhook_event'),
        ),
    ]
