# Generated by Django 5.2.5 on 2026-09-09 16:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0071_credittransaction_source_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlessonitem',
            name='student_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='batchlessonitem',
            name='teacher_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='historicallesson',
            name='student_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Rate billed to student for this lesson', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='historicallesson',
            name='teacher_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Rate paid to teacher for this lesson', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Rate billed to student for this lesson', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Rate paid to teacher for this lesson', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
