# Generated by Django 5.2.5 on 2026-09-10 18:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0072_rate_min_value_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallesson',
            name='student_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate billed to student for this lesson', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='historicallesson',
            name='teacher_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate paid to teacher for this lesson', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate billed to student for this lesson', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate paid to teacher for this lesson', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
