# Generated by Django 5.2.5 on 2026-09-10 18:52
#
# MAP-186: every CreditTransaction row must carry a source reference
# (credit_transaction_has_source). Rows that already exist at migration time
# have every source NULL, so the constraint can only be added after they are
# marked legacy=True (readiness audit R6). History is NOT rewritten: legacy
# approval-time 'forfeited' rows that moved balance cannot be told apart from
# payroll-time ones, so the ledger invariant
#   balance == Σ(pre_billing_payment + waived_rollover) − Σ(lesson_charge)
# is asserted for accounts created after this migration and enforced going
# forward. Reverse: constraint and fields drop; the legacy flag data step is a
# no-op backwards.

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_rows_legacy(apps, schema_editor):
    CreditTransaction = apps.get_model('billing', 'CreditTransaction')
    CreditTransaction.objects.update(legacy=True)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0073_lesson_rates_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='legacy',
            field=models.BooleanField(default=False, help_text='Row predates the source requirement (migration 0074). Never set by ledger.post.'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='source_batch_item',
            field=models.ForeignKey(blank=True, help_text='Batch lesson item this row was posted against (approval charge, forfeit, rollover).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='billing.batchlessonitem'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='source_invoice',
            field=models.ForeignKey(blank=True, help_text='Pre-billing invoice this row was posted against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='billing.prebillinginvoice'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='source_lesson',
            field=models.ForeignKey(blank=True, help_text='Lesson this row was posted against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='billing.lesson'),
        ),
        migrations.AddField(
            model_name='historicalcredittransaction',
            name='legacy',
            field=models.BooleanField(default=False, help_text='Row predates the source requirement (migration 0074). Never set by ledger.post.'),
        ),
        migrations.AddField(
            model_name='historicalcredittransaction',
            name='source_batch_item',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Batch lesson item this row was posted against (approval charge, forfeit, rollover).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.batchlessonitem'),
        ),
        migrations.AddField(
            model_name='historicalcredittransaction',
            name='source_invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Pre-billing invoice this row was posted against.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.prebillinginvoice'),
        ),
        migrations.AddField(
            model_name='historicalcredittransaction',
            name='source_lesson',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lesson this row was posted against.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.lesson'),
        ),
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='issued_items',
            field=models.JSONField(blank=True, help_text='Line items as issued (written at send time, rewritten on lesson removal). A sent/adjusted/paid invoice displays only this snapshot; it is never re-projected from current schedules (MAP-186).', null=True),
        ),
        migrations.AddField(
            model_name='historicalstudentcreditaccount',
            name='needs_attention',
            field=models.BooleanField(default=False, help_text="Set when a batch approval could not be fully covered by the balance (a 'shortfall' ledger row was posted). Cleared manually."),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='issued_items',
            field=models.JSONField(blank=True, help_text='Line items as issued (written at send time, rewritten on lesson removal). A sent/adjusted/paid invoice displays only this snapshot; it is never re-projected from current schedules (MAP-186).', null=True),
        ),
        migrations.AddField(
            model_name='studentcreditaccount',
            name='needs_attention',
            field=models.BooleanField(default=False, help_text="Set when a batch approval could not be fully covered by the balance (a 'shortfall' ledger row was posted). Cleared manually."),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='type',
            field=models.CharField(choices=[('pre_billing_payment', 'Pre-Billing Payment'), ('forfeited', 'Forfeited'), ('waived_rollover', 'Waived Rollover'), ('lesson_charge', 'Lesson Charge'), ('shortfall', 'Shortfall')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcredittransaction',
            name='type',
            field=models.CharField(choices=[('pre_billing_payment', 'Pre-Billing Payment'), ('forfeited', 'Forfeited'), ('waived_rollover', 'Waived Rollover'), ('lesson_charge', 'Lesson Charge'), ('shortfall', 'Shortfall')], max_length=30),
        ),
        migrations.RunPython(mark_existing_rows_legacy, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('legacy', True), ('source_event__isnull', False), ('source_invoice__isnull', False), ('source_batch_item__isnull', False), ('source_lesson__isnull', False), _connector='OR'), name='credit_transaction_has_source'),
        ),
    ]
