# MAP-184: lesson removal preserves credit and never orphans a cancelled
# Helcim invoice.
#
# PreBillingInvoice gains previous_helcim_invoice_id/number (the invoice the
# replacement superseded), revision (incremented per removal) and
# cancel_outcome (none|pending|done|failed — whether the previous invoice was
# voided; 'failed' is retried from admin). HelcimWebhookEvent.processing_status
# gains the terminal 'needs_attention' state for a payment on a superseded
# number. The amount help_text drops the superseded D-11 wording. Shadow
# (historical*) tables carry the same fields. Reverse drops the fields; no
# data step.

# Generated by Django 5.2.5 on 2026-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0075_batch_invoice_one_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='cancel_outcome',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='none', help_text='Outcome of voiding previous_helcim_invoice_id after the last removal (MAP-184).', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='previous_helcim_invoice_id',
            field=models.CharField(blank=True, help_text='Helcim invoice ID this invoice replaced on the last lesson removal (MAP-184). The one cancel_outcome refers to.', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='previous_helcim_invoice_number',
            field=models.CharField(blank=True, help_text='Helcim invoiceNumber this invoice replaced. A payment webhook on this number is finalized needs_attention and never credited.', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='revision',
            field=models.PositiveIntegerField(default=0, help_text='Incremented on every lesson removal (replacement Helcim invoice).'),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='cancel_outcome',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='none', help_text='Outcome of voiding previous_helcim_invoice_id after the last removal (MAP-184).', max_length=10),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='previous_helcim_invoice_id',
            field=models.CharField(blank=True, help_text='Helcim invoice ID this invoice replaced on the last lesson removal (MAP-184). The one cancel_outcome refers to.', max_length=100),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='previous_helcim_invoice_number',
            field=models.CharField(blank=True, help_text='Helcim invoiceNumber this invoice replaced. A payment webhook on this number is finalized needs_attention and never credited.', max_length=100),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='revision',
            field=models.PositiveIntegerField(default=0, help_text='Incremented on every lesson removal (replacement Helcim invoice).'),
        ),
        migrations.AlterField(
            model_name='helcimwebhookevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('credited_partial', 'Credited (partial)'), ('not_approved', 'Not approved'), ('non_purchase', 'Non-purchase'), ('no_invoice', 'No matching invoice'), ('no_account', 'No credit account'), ('enrichment_failed', 'Enrichment failed'), ('needs_attention', 'Needs attention')], default='pending', help_text='Outcome of credit reconciliation. Retryable states are re-attempted on webhook retry or via retry_webhook_events.', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalhelcimwebhookevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('credited_partial', 'Credited (partial)'), ('not_approved', 'Not approved'), ('non_purchase', 'Non-purchase'), ('no_invoice', 'No matching invoice'), ('no_account', 'No credit account'), ('enrichment_failed', 'Enrichment failed'), ('needs_attention', 'Needs attention')], default='pending', help_text='Outcome of credit reconciliation. Retryable states are re-attempted on webhook retry or via retry_webhook_events.', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalprebillinginvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount the parent is asked to pay: gross of the issued lessons minus applied wallet credit. Recomputed on lesson removal (MAP-184). Floor at 0 enforced in view layer (D-05).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='prebillinginvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount the parent is asked to pay: gross of the issued lessons minus applied wallet credit. Recomputed on lesson removal (MAP-184). Floor at 0 enforced in view layer (D-05).', max_digits=10),
        ),
    ]
