# MAP-185: sends are reconciled, never duplicated, never stranded in
# 'sending'.
#
# PreBillingInvoice gains send_attempt_id (uuid written by the send claim; the
# Helcim invoiceNumber for that attempt is MK{pk}-{hex[:8]}) and send_outcome
# (none|unknown|failed|sent — 'unknown' means look the previous number up
# before creating again; 'failed' is declared, no transition writes it yet).
# Shadow (historical) table carries both. Reverse drops the fields; no data
# step. Rows already stuck in 'sending' before this migration keep
# send_outcome='none' and are not claimable — none exist in production.

# Generated by Django 5.2.5 on 2026-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0076_prebilling_adjustment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='send_attempt_id',
            field=models.UUIDField(blank=True, help_text="Attempt id written by the send claim (MAP-185). The Helcim invoiceNumber for that attempt is MK{pk}-{hex[:8]}; a retry looks the previous attempt's number up before creating again.", null=True),
        ),
        migrations.AddField(
            model_name='historicalprebillinginvoice',
            name='send_outcome',
            field=models.CharField(choices=[('none', 'None'), ('unknown', 'Unknown'), ('failed', 'Failed'), ('sent', 'Sent')], default='none', help_text="Where the last send attempt got to. Never returns to 'none' once an attempt started; 'unknown' means look the number up before creating again (MAP-185).", max_length=10),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='send_attempt_id',
            field=models.UUIDField(blank=True, help_text="Attempt id written by the send claim (MAP-185). The Helcim invoiceNumber for that attempt is MK{pk}-{hex[:8]}; a retry looks the previous attempt's number up before creating again.", null=True),
        ),
        migrations.AddField(
            model_name='prebillinginvoice',
            name='send_outcome',
            field=models.CharField(choices=[('none', 'None'), ('unknown', 'Unknown'), ('failed', 'Failed'), ('sent', 'Sent')], default='none', help_text="Where the last send attempt got to. Never returns to 'none' once an attempt started; 'unknown' means look the number up before creating again (MAP-185).", max_length=10),
        ),
    ]
