# MAP-154: unattended reconciliation scheduler.
#
# School.helcim_last_synced_at is the sync_helcim_payments checkpoint — the
# newest Helcim dateCreated reconciled for that school. Null = never synced;
# the first run looks back 30 days. The shadow table (historicalschool)
# carries the same field. Reverse drops it; no data step.

# Generated by Django 5.2.5 on 2026-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0077_prebilling_send_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschool',
            name='helcim_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='sync_helcim_payments checkpoint (MAP-154): the newest Helcim dateCreated reconciled for this school. Null = never synced; the first run looks back 30 days.', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='helcim_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='sync_helcim_payments checkpoint (MAP-154): the newest Helcim dateCreated reconciled for this school. Null = never synced; the first run looks back 30 days.', null=True),
        ),
    ]
