# MAP-141: auth lifecycle.
#
# User.password_changed_at is stamped on password reset and on management
# deactivation; custom_auth.authentication.JWTAuthentication rejects access
# tokens whose iat precedes it (whole-second comparison, D5), and the same
# moment blacklists every outstanding refresh token. Null = never changed
# through those paths. The shadow table (historicaluser) carries the field.
# Reverse drops it; no data step.

# Generated by Django 5.2.5 on 2026-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0078_school_helcim_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
