# Generated by Django 5.2.5 on 2026-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0079_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecurringlessonsschedule',
            name='interval_weeks',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Weekly'), (2, 'Every 2 weeks')], default=1, help_text='1 = every week, 2 = every other week, counted from start_date'),
        ),
        migrations.AddField(
            model_name='recurringlessonsschedule',
            name='interval_weeks',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Weekly'), (2, 'Every 2 weeks')], default=1, help_text='1 = every week, 2 = every other week, counted from start_date'),
        ),
    ]
