# Generated by Django 5.2.5 on 2026-09-21 22:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0080_recurringschedule_interval_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='helcimwebhookevent',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Part of amount above what the invoice still owed (e.g. card convenience fee). Never credited to the wallet (MAP-216).', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalhelcimwebhookevent',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Part of amount above what the invoice still owed (e.g. card convenience fee). Never credited to the wallet (MAP-216).', max_digits=10),
        ),
    ]
