# Generated by Django 5.2.5 on 2026-09-26 22:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0081_helcimwebhookevent_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='online_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='online_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
