# Generated by Django 5.2.5 on 2026-09-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0082_user_online_hourly_rate'),
        # MAP-229: the column is dropped only after its values are copied into rows.
        ('teacher_profiles', '0005_backfill_user_instruments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instruments',
        ),
    ]
