# Generated by Django 5.2.5 on 2026-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0083_remove_user_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolsettings',
            name='invoice_reply_to_email',
            field=models.EmailField(blank=True, help_text='Reply-To for parent invoice emails; blank = replies go to the sending address', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='invoice_reply_to_email',
            field=models.EmailField(blank=True, help_text='Reply-To for parent invoice emails; blank = replies go to the sending address', max_length=254),
        ),
    ]
