# Generated by Django 5.2.5 on 2026-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0083_remove_user_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschool',
            name='map164_drill_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='map164_drill_flag',
            field=models.BooleanField(default=False),
        ),
    ]
