# Generated by Django 5.2.17 on 2026-09-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0084_schoolsettings_invoice_reply_to_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="postal_code",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("YT", "Yukon"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("YT", "Yukon"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
