# Generated by Django 5.2.5 on 2026-07-07 02:18

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0058_recurringschedule_pause_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('advertising', 'Advertising'), ('payroll', 'Payroll (non-teacher)'), ('infrastructure', 'Digital Infrastructure'), ('rent', 'Rent & Facilities'), ('supplies', 'Supplies & Equipment'), ('other', 'Other')], max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_tag', to='billing.schoolexpenseitem')),
            ],
            options={
                'verbose_name_plural': 'expense item categories',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMetricGoal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('metric', models.CharField(choices=[('mrr', 'Monthly Recurring Revenue'), ('gross_margin', 'Gross Margin'), ('active_students', 'Active Students'), ('new_enrollments', 'New Enrollments / Month'), ('churn_rate', 'Churn Rate %'), ('trial_conversion', 'Trial Conversion %')], max_length=30)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical metric goal',
                'verbose_name_plural': 'historical metric goals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudentExitRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reason', models.CharField(choices=[('schedule_conflict', 'Schedule Conflict'), ('price', 'Price'), ('moved', 'Moved Away'), ('teacher_fit', 'Teacher Fit'), ('lost_interest', 'Lost Interest'), ('finished_goals', 'Finished Goals'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.school')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student exit record',
                'verbose_name_plural': 'historical student exit records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ScheduleInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_tag', to='billing.recurringlessonsschedule')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('schedule_conflict', 'Schedule Conflict'), ('price', 'Price'), ('moved', 'Moved Away'), ('teacher_fit', 'Teacher Fit'), ('lost_interest', 'Lost Interest'), ('finished_goals', 'Finished Goals'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_exit_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_exit_records', to='billing.school')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('mrr', 'Monthly Recurring Revenue'), ('gross_margin', 'Gross Margin'), ('active_students', 'Active Students'), ('new_enrollments', 'New Enrollments / Month'), ('churn_rate', 'Churn Rate %'), ('trial_conversion', 'Trial Conversion %')], max_length=30)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_goals', to='billing.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_metric_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'metric'), name='unique_goal_per_school_metric')],
            },
        ),
    ]
