"""
Django settings for maple_key_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config  # For reading environment variables from .env file
from urllib.parse import urlparse
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Using config() to read from .env file for security - never commit secrets to git
# No default value - forces proper .env setup
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should be False in production for security
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS configuration
# Read from environment variable or use safe defaults for development
ALLOWED_HOSTS_STR = config('ALLOWED_HOSTS', default='localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]


# CORS configuration
cors_allowed_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_allowed_str:
    if cors_allowed_str == '*':
        CORS_ALLOW_ALL_ORIGINS = True
    else:
        CORS_ALLOWED_ORIGINS = [host.strip() for host in cors_allowed_str.split(',')]
else:
    # Default: Allow your frontend domain
    CORS_ALLOWED_ORIGINS = []


# SSL/HTTPS Security Settings
# These settings ensure your Django app works properly behind an HTTPS proxy (Nginx)

# Trust the X-Forwarded-Proto header from Nginx to determine if request was HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Only enable these in production (when DEBUG=False)
if not DEBUG:
    # Redirect all HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = True

    # Use secure cookies (only sent over HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Session cookie settings for OAuth flow
    SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cookies in OAuth redirects
    CSRF_COOKIE_SAMESITE = 'Lax'

    # HTTP Strict Transport Security (HSTS)
    # Tells browsers to always use HTTPS for this domain (for 1 year)
    SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
    SECURE_HSTS_PRELOAD = True  # Allow preloading in browsers


# Application definition

INSTALLED_APPS = [
    'billing.apps.BillingConfig',  # Use full app config path to trigger ready() method for signals
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'simple_history',  # Audit logging for model changes

    # Custom authentication app
    'custom_auth',  # Your custom auth app for OAuth views and JWT handling

    # Teacher professional profiles (instruments, availability, location)
    'teacher_profiles',

    # In-app notifications (bell dropdown) — full path so ready() connects signals
    'notifications.apps.NotificationsConfig',
    # Dashboard analytics (read-only aggregation + side-table capture models)
    'analytics',

    # Observability
    # Prometheus metrics - exposes /metrics endpoint for Prometheus scraping
    'django_prometheus',
    # Health checks - exposes /health/ endpoint for container orchestration
    'health_check',                     # Core health check
    'health_check.db',                  # Database connectivity check
    'health_check.cache',               # Cache backend check
    'health_check.storage',             # Storage backend check
    'health_check.contrib.migrations',  # Pending migrations check
    'health_check.contrib.psutil',      # System resources (CPU, memory, disk)
]

MIDDLEWARE = [
    # Prometheus middleware (must be first to capture all requests)
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",  # Tracks user for audit logging
    # Prometheus middleware (must be last to capture response metrics)
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = "maple_key_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "maple_key_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# Try to get DATABASE_URL first (for production), fall back to individual vars (for local dev)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Production: Parse DATABASE_URL (from Docker environment)
    # Format: postgresql://user:password@host:port/dbname
    url = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path[1:],  # Remove leading slash
            'USER': url.username,
            'PASSWORD': url.password,
            'HOST': url.hostname,
            'PORT': url.port or 5432,
        }
    }
else:
    # Local development: Use individual environment variables
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config('POSTGRES_DB', default='maple_key_dev'),
            "USER": config('POSTGRES_USER', default='maple_key_user'),
            "PASSWORD": config('POSTGRES_PASSWORD', default='maple_key_password'),
            "HOST": config('POSTGRES_HOST', default='127.0.0.1'),
            "PORT": config('POSTGRES_PORT', default='5432'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# JWT (JSON Web Token) Settings
# These settings control how JWT tokens are created and validated
from datetime import timedelta

SIMPLE_JWT = {
    # Token lifetime settings
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # How long access tokens are valid (60 minutes)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # How long refresh tokens are valid (1 day)
    'ROTATE_REFRESH_TOKENS': False,                  # Whether to create new refresh tokens when used
    'BLACKLIST_AFTER_ROTATION': True,                # Blacklist old tokens after rotation
    'UPDATE_LAST_LOGIN': False,                      # Whether to update user's last login time

    # Token signing settings
    'ALGORITHM': 'HS256',                            # Algorithm used to sign tokens (HMAC with SHA-256)
    'SIGNING_KEY': SECRET_KEY,                       # Key used to sign tokens (your Django secret key)
    'VERIFYING_KEY': None,                           # Key used to verify tokens (None for symmetric algorithms)
    'AUDIENCE': None,                                # Expected audience in token (None for no validation)
    'ISSUER': None,                                  # Expected issuer in token (None for no validation)

    # HTTP header settings
    'AUTH_HEADER_TYPES': ('Bearer',),                # Authorization header type (Bearer token)
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',        # Name of the authorization header
    'USER_ID_FIELD': 'id',                           # Field in user model that contains user ID
    'USER_ID_CLAIM': 'user_id',                      # Claim name for user ID in token

    # Token class settings
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),  # Token classes to use
    'TOKEN_TYPE_CLAIM': 'token_type',                # Claim name for token type

    # JWT ID claim
    'JTI_CLAIM': 'jti',                              # Claim name for JWT ID (unique identifier)
}

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Frontend URL (used by PKCE OAuth exchange and password reset)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# CSRF settings
# Add both HTTP (for local dev) and HTTPS (for production)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://api.maplekeymusic.com",  # Production HTTPS domain
]

# CORS settings (only used if CORS_ALLOWED_ORIGINS env var is not set - see line 42-50)
# In production, CORS_ALLOWED_ORIGINS is set via environment variable
# These are fallback values for local development
if not CORS_ALLOWED_ORIGINS:  # Only set if not already set by environment variable
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]

# Additional CORS settings for credentials and headers
CORS_ALLOW_CREDENTIALS = True  # Allow cookies/auth headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT token authentication
        'rest_framework.authentication.SessionAuthentication',  # Session-based authentication (for admin/built in django auth)
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Require authentication for write operations
    ],
    # Scoped throttles only — applied per-view via ScopedRateThrottle
    # (registration is an open, unauthenticated form; bots hammer open forms)
    'DEFAULT_THROTTLE_RATES': {
        'registration': '5/hour',
        'client_errors': '30/hour',
    },
}

# Custom User Model
AUTH_USER_MODEL = 'billing.User'

# Email Configuration
# Use Resend HTTP API backend (avoids SMTP port blocking issues)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='billing.resend_backend.ResendEmailBackend')

# Resend API Key (for HTTP API - not SMTP)
RESEND_API_KEY = config('RESEND_API_KEY', default='')

# Legacy SMTP settings (kept for reference, but not used with Resend HTTP API)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.resend.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='resend')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@maplekey.com')
TEST_EMAIL_RECIPIENT = config('TEST_EMAIL_RECIPIENT', default='antonilueddeke@gmail.com')

# --- Helcim (Phase 18) ---
# Hard fail-fast on missing values is in billing/apps.py:BillingConfig.ready().
# default=None here is intentional — None is unambiguous for downstream if/not checks.
# Consumed by billing/services/helcim_client.py (Plan 01) and billing/views/webhooks.py (Plan 03).
HELCIM_API_TOKEN = config('HELCIM_API_TOKEN', default=None)
HELCIM_TERMINAL_ID = config('HELCIM_TERMINAL_ID', default=None)
HELCIM_WEBHOOK_SECRET = config('HELCIM_WEBHOOK_SECRET', default=None)
HELCIM_SUBDOMAIN = config('HELCIM_SUBDOMAIN', default=None)

# --- Test-data filtering (MAP-113) ---
# When ANALYTICS_EXCLUDE_TEST_DATA is true (production), analytics aggregations
# exclude rows tied to accounts whose email ends with one of these domains.
# Off by default so dev/UAT can watch test data populate the dashboard.
ANALYTICS_EXCLUDE_TEST_DATA = config(
    'ANALYTICS_EXCLUDE_TEST_DATA', default=False, cast=bool
)
TEST_ACCOUNT_EMAIL_DOMAINS = [
    d.strip().lstrip('@')
    for d in config('TEST_ACCOUNT_EMAIL_DOMAINS', default='maplekeytest.com').split(',')
    if d.strip()
]

# --- Health checks (django-health-check) ---
# Endpoints for container orchestration — /health/ (HTML) or /health/?format=json
HEALTH_CHECK = {
    # Disk usage threshold - warn if disk is more than 90% full
    'DISK_USAGE_MAX': 90,
    # Minimum free memory in MB
    'MEMORY_MIN': 100,
}

# --- Prometheus metrics (django-prometheus) ---
# Exposes /metrics for Prometheus scraping: request counts, latencies,
# database queries, cache hits, etc.
PROMETHEUS_EXPORT_MIGRATIONS = False  # Disable migration metrics to reduce noise

# Structured logging — JSON lines to stdout on every environment so Promtail
# can ship them to Loki and filter by level, logger name, etc. without regex.
# File handler built conditionally: RotatingFileHandler requires /var/log/maple-key/
# to exist and must not be instantiated in local dev or CI (DEBUG=True).
_log_formatters = {
    'json': {
        '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
        'format': '%(asctime)s %(levelname)s %(name)s %(message)s %(pathname)s %(lineno)d',
    },
}

_log_handlers = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'json',
    },
}
if not DEBUG:
    _log_handlers['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': '/var/log/maple-key/app.log',
        'maxBytes': 10 * 1024 * 1024,  # 10 MB
        'backupCount': 5,
        'formatter': 'json',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': _log_formatters,
    'handlers': _log_handlers,
    'loggers': {
        'django': {
            'handlers': ['console'] if DEBUG else ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'] if DEBUG else ['console', 'file'],
            'level': 'WARNING',  # Avoid double-logging successful requests (Prometheus already tracks these)
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'] if DEBUG else ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'] if DEBUG else ['console', 'file'],
        'level': 'INFO',
    },
}
