"""
Django settings for maple_key_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config  # For reading environment variables from .env file
from urllib.parse import urlparse
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Using config() to read from .env file for security - never commit secrets to git
# No default value - forces proper .env setup
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should be False in production for security
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS configuration
# Read from environment variable or use safe defaults for development
ALLOWED_HOSTS_STR = config('ALLOWED_HOSTS', default='localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]


# CORS configuration
cors_allowed_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_allowed_str:
    if cors_allowed_str == '*':
        CORS_ALLOW_ALL_ORIGINS = True
    else:
        CORS_ALLOWED_ORIGINS = [host.strip() for host in cors_allowed_str.split(',')]
else:
    # Default: Allow your frontend domain
    CORS_ALLOWED_ORIGINS = []


# SSL/HTTPS Security Settings
# These settings ensure your Django app works properly behind an HTTPS proxy (Nginx)

# Trust the X-Forwarded-Proto header from Nginx to determine if request was HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Only enable these in production (when DEBUG=False)
if not DEBUG:
    # Redirect all HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = True

    # Use secure cookies (only sent over HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Session cookie settings for OAuth flow
    SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cookies in OAuth redirects
    CSRF_COOKIE_SAMESITE = 'Lax'

    # HTTP Strict Transport Security (HSTS)
    # Tells browsers to always use HTTPS for this domain (for 1 year)
    SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
    SECURE_HSTS_PRELOAD = True  # Allow preloading in browsers


# Application definition

INSTALLED_APPS = [
    'billing.apps.Test1Config',  # Use full app config path to trigger ready() method for signals
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework', 
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders', 
    
    # Django Allauth - Required for OAuth authentication
    'django.contrib.sites',  # Required by django-allauth for multi-site support
    'allauth',  # Main allauth app for authentication
    'allauth.account',  # Handles user accounts and registration
    'allauth.socialaccount',  # Handles social media authentication
    'allauth.socialaccount.providers.google',  # Google OAuth provider
    
    # Custom authentication app
    'custom_auth',  # Your custom auth app for OAuth views and JWT handling
]

MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Required by django-allauth
]

ROOT_URLCONF = "maple_key_backend.urls"

# Site ID - Required by django-allauth for multi-site support
# This identifies which site in the database this Django instance represents
SITE_ID = 2

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "maple_key_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# Try to get DATABASE_URL first (for production), fall back to individual vars (for local dev)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Production: Parse DATABASE_URL (from Docker environment)
    # Format: postgresql://user:password@host:port/dbname
    url = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path[1:],  # Remove leading slash
            'USER': url.username,
            'PASSWORD': url.password,
            'HOST': url.hostname,
            'PORT': url.port or 5432,
        }
    }
else:
    # Local development: Use individual environment variables
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config('POSTGRES_DB', default='maple_key_dev'),
            "USER": config('POSTGRES_USER', default='maple_key_user'),
            "PASSWORD": config('POSTGRES_PASSWORD', default='maple_key_password'),
            "HOST": config('POSTGRES_HOST', default='127.0.0.1'),
            "PORT": config('POSTGRES_PORT', default='5432'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# JWT (JSON Web Token) Settings
# These settings control how JWT tokens are created and validated
from datetime import timedelta

SIMPLE_JWT = {
    # Token lifetime settings
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # How long access tokens are valid (60 minutes)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # How long refresh tokens are valid (1 day)
    'ROTATE_REFRESH_TOKENS': False,                  # Whether to create new refresh tokens when used
    'BLACKLIST_AFTER_ROTATION': True,                # Blacklist old tokens after rotation
    'UPDATE_LAST_LOGIN': False,                      # Whether to update user's last login time

    # Token signing settings
    'ALGORITHM': 'HS256',                            # Algorithm used to sign tokens (HMAC with SHA-256)
    'SIGNING_KEY': SECRET_KEY,                       # Key used to sign tokens (your Django secret key)
    'VERIFYING_KEY': None,                           # Key used to verify tokens (None for symmetric algorithms)
    'AUDIENCE': None,                                # Expected audience in token (None for no validation)
    'ISSUER': None,                                  # Expected issuer in token (None for no validation)

    # HTTP header settings
    'AUTH_HEADER_TYPES': ('Bearer',),                # Authorization header type (Bearer token)
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',        # Name of the authorization header
    'USER_ID_FIELD': 'id',                           # Field in user model that contains user ID
    'USER_ID_CLAIM': 'user_id',                      # Claim name for user ID in token

    # Token class settings
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),  # Token classes to use
    'TOKEN_TYPE_CLAIM': 'token_type',                # Claim name for token type

    # JWT ID claim
    'JTI_CLAIM': 'jti',                              # Claim name for JWT ID (unique identifier)
}

# Django Allauth Settings
# These settings configure how django-allauth handles authentication

# Authentication backends - order matters!
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',     # Django's default authentication backend
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth's authentication backend
]

# Account settings (for allauth.account) - Updated to new format
ACCOUNT_UNIQUE_EMAIL = True                          # Email addresses must be unique
ACCOUNT_EMAIL_VERIFICATION = 'none'                  # Email verification setting ('none', 'optional', 'mandatory')
ACCOUNT_LOGIN_METHODS = {'email'}                    # Use email for authentication instead of username
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Required fields for signup

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@maplekeymusic.com')

# Social account settings (for allauth.socialaccount)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',  # Access to user's basic profile info
            'email',    # Access to user's email address
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',  # Type of access ('online' or 'offline')
        },
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_CLIENT_SECRET'),
            'key': ''
        }
    }
}

# Django Allauth settings
# Dynamic redirect based on environment
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')
LOGIN_REDIRECT_URL = f'{FRONTEND_URL}/dashboard'
SOCIALACCOUNT_LOGIN_ON_GET = True

# CSRF settings
# Add both HTTP (for local dev) and HTTPS (for production)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://api.maplekeymusic.com",  # Production HTTPS domain
]

# CORS settings (only used if CORS_ALLOWED_ORIGINS env var is not set - see line 42-50)
# In production, CORS_ALLOWED_ORIGINS is set via environment variable
# These are fallback values for local development
if not CORS_ALLOWED_ORIGINS:  # Only set if not already set by environment variable
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]

# Additional CORS settings for credentials and headers
CORS_ALLOW_CREDENTIALS = True  # Allow cookies/auth headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT token authentication
        'rest_framework.authentication.SessionAuthentication',  # Session-based authentication (for admin/built in django auth)
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Require authentication for write operations
    ],
}

# Custom User Model
AUTH_USER_MODEL = 'billing.User'

# Email Configuration
# Use Resend HTTP API backend (avoids SMTP port blocking issues)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='billing.resend_backend.ResendEmailBackend')

# Resend API Key (for HTTP API - not SMTP)
RESEND_API_KEY = config('RESEND_API_KEY', default='')

# Legacy SMTP settings (kept for reference, but not used with Resend HTTP API)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.resend.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='resend')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@maplekey.com')
TEST_EMAIL_RECIPIENT = config('TEST_EMAIL_RECIPIENT', default='antonilueddeke@gmail.com')
