"""
Render custom_auth/route_manifest.py as a markdown route x role matrix (MAP-143).

Usage (from the backend root, inside the api container):

    python scripts/route_role_matrix.py > route-role-matrix.md

One row per resolvable route: name, path, HTTP methods, who may call it, and
the view's source file:line. The manifest is the source of truth; the test
tests/integration/custom_auth/test_route_auth_manifest.py proves the live
behaviour matches it.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'maple_key_backend.settings')

import django  # noqa: E402

django.setup()

from custom_auth.route_manifest import (  # noqa: E402
    MANAGEMENT,
    ROUTE_MANIFEST,
    STUDENT,
    TEACHER,
    iter_routes,
)

ROLE_ORDER = (STUDENT, TEACHER, MANAGEMENT)


def access(entry):
    if entry is None:
        return '**MISSING FROM MANIFEST**'
    if isinstance(entry, frozenset):
        return ', '.join(role for role in ROLE_ORDER if role in entry)
    return entry


def main():
    routes = list(iter_routes())
    lines = [
        '# Route x role matrix',
        '',
        'Generated by `scripts/route_role_matrix.py` from '
        '`custom_auth/route_manifest.py`. Enforced by '
        '`tests/integration/custom_auth/test_route_auth_manifest.py` '
        '(anonymous -> 401, role outside the set -> 403, role inside -> '
        'not 401/403). Ownership (teacher A vs teacher B) and school scoping '
        'are not covered by the manifest.',
        '',
        f'{len(routes)} routes.',
        '',
        '| Route | Path | Methods | Access | Source |',
        '|---|---|---|---|---|',
    ]
    for route in routes:
        lines.append(
            f'| `{route.name}` | `/{route.path}` | {" ".join(route.methods) or "-"} '
            f'| {access(ROUTE_MANIFEST.get(route.name))} | '
            f'{route.source() or "-"} |'
        )
    print('\n'.join(lines))


if __name__ == '__main__':
    main()
