# Generated by Django 5.2.5 on 2026-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invoice_rejected', 'Invoice Rejected'), ('invoice_reminder', 'Invoice Submission Reminder'), ('batch_submitted', 'Invoice Submitted'), ('exception_marked', 'Exception Marked'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
